language: node_js
node_js:
  - "node"
services:
  - mysql
before_script:
  - cd $TRAVIS_BUILD_DIR/backend
  - cp ./test/config.test.json ./src/config.json
  - npm install
  - cd test
  - ./setupTestEnv.sh
matrix:
  include:
  - name: "Frontend"
    addons:
      chrome: beta 
    script:  
    - cd $TRAVIS_BUILD_DIR/backend
    - npm start&
    - sleep 10
    - cd $TRAVIS_BUILD_DIR/frontend/test
    - ./setup-nginx.sh
    - cd ..
    - cp ./test/config.test.json ./config.json
    - npm install
    - (npm run dev > /dev/null 2>&1)&
    - sleep 10
    - npm test
  - name: "Backend"
    script:  
      - cd $TRAVIS_BUILD_DIR/backend
      - npm test
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
