language: node_js
addons:
  chrome: stable
node_js:
  - "node"
services:
  - mysql
before_script:
  - cd $TRAVIS_BUILD_DIR/test
  - ./setup-tests.sh
matrix:
  include:
  - name: "Frontend"
    script:  
    - cd $TRAVIS_BUILD_DIR/backend/test/
    - ./setupTestEnv.sh
    - cp ./test/config.test.json ./src/config.json
    - npm test
  - name: "Backend"
  script:  
    - cd $TRAVIS_BUILD_DIR/frontend
    - npm test
