language: node_js
node_js:
  - "node"
services:
  - mysql
script:
  - cd backend/src
  - cp tests/config.test.json ./config.json
  - mysql -e 'CREATE DATABASE slate;'
  - cat migrations/* | mysql slate
  - cat src/tests/slate.test.sql | mysql slate
  - npm install
  - npm test
