language: node_js
node_js:
  - "node"
services:
  - mysql
script:
  - cd backend
  - cp ./test/config.test.json ./src/config.json
  - mysql -e 'CREATE DATABASE slate;'
  - cat migrations/* | mysql slate
  - cat src/tests/slate.test.sql | mysql slate
  - npm install
  - npm test
