language: node_js
addons:
  chrome: stable
node_js:
  - "node"
services:
  - mysql
before_script:
  - sudo apt-get update
  - sudo apt-get install nginx
  - nginx -c $TRAVIS_BUILD_DIR/frontend/test/slate.nginx.test.conf
script:
  - cd backend/test/
  - ./setupTestEnv.sh
  - cd ../
  - cp ./test/config.test.json ./src/config.json
  - npm install
  - npm test
  - cd ../frontend
  - npm install
  - npm test