language: node_js
addons:
  chrome: stable
node_js:
  - "node"
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
services:
  - mysql
script:
  - cd backend/test/
  - ./setupTestEnv.sh
  - cd ../
  - cp ./test/config.test.json ./src/config.json
  - npm install
  - npm test
  - cd ../frontend
  - npm install
  - npm test