language: node_js
addons:
  chrome: stable
node_js:
  - "node"
services:
  - mysql
script:
  - cd backend/test/
  - ./setupTestEnv.sh
  - cd ../
  - cp ./test/config.test.json ./src/config.json
  - npm install
  - npm test