language: node_js
addons:
  chrome: stable
node_js:
  - "node"
services:
  - mysql
before_script:
  - cd $TRAVIS_BUILD_DIR/frontend/test/
  - ./setup-nginx.sh
script:
  - cd backend/test/
  - ./setupTestEnv.sh
  - cd ../
  - cp ./test/config.test.json ./src/config.json
  - npm install
  - npm test
  - cd ../frontend
  - npm install
  - npm test