language: node_js
node_js:
  - "node"
services:
  - mysql
script:
  - cd backend
  - cp src/tests/mysqlCreds.test.json ./mysqlCreds.json
  - cp src/tests/sendgrid.test.json ./sendgrid.json
  - cp src/tests/emailCreds.test.json ./emailCreds.json
  - mysql -e 'CREATE =ATABASE slate;'
  - cat migrations/* | mysql slate
  - cat src/tests/slate.test.sql | mysql slate
  - npm install
  - npm test