ALTER TABLE subjects DROP COLUMN dark_color;
ALTER TABLE users MODIFY COLUMN valid_email BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE users MODIFY COLUMN password_reset BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN theme VARCHAR(10) NOT NULL DEFAULT 'light';
